### ISSUE TITLE
关于shardkv中的问题

### ISSUE THREAD

**Issue by DJH199** [tjumcw/6.824#8]
您好，大佬，就是在shardkv中，server中并没有与shardmaster相关联，也没有创建RPC server去bind join，query，move，leave，这是为什么呢？

**Comment by tjumcw** [comment]
您好，shardkv中组合了一个shardClerk对象，用来向server发起join，query，move，leave等请求，shardmaster是一个独立的server集群吧，你可以仔细看下LAB4A的readme

**Comment by DJH199** [comment]
好的，谢谢佬了
